const supabaseUrl="https://euyqvisqgxuwzcswwiqf.supabase.co";
const supabaseKey="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV1eXF2c3N4Z3h1d3pjc3d3aXFpZiIsImlhdCI6MTc4Njg0Njc5MiwiZXhwIjoyMTAyNDIyNzk5Mn0.9QjLUxFdiy-D92hImFtLuPcLQ81b47YK9PgyfwgjELc";
const client=window.supabase.createClient(supabaseUrl,supabaseKey,{auth:{persistSession:true,autoRefreshToken:true}});
function sleep(ms){return new Promise(resolve=>setTimeout(resolve,ms));}
async function getCurrentSession(){let lastError=null;for(let attempt=0;attempt<4;attempt++){const {data,error}=await client.auth.getSession();if(data&&data.session)return{session:data.session,user:data.session.user,error:null};lastError=error||new Error("No active session.");if(attempt<3)await sleep(400*(attempt+1));}return{session:null,user:null,error:lastError};}
async function getCurrentUserProfile(){const {session,user,error:sessionError}=await getCurrentSession();if(sessionError||!session||!user)return{session:null,user:null,profile:null,error:sessionError||new Error("No active session.")};const {data:profile,error}=await client.from("user_profiles").select("id, full_name, role, active").eq("id",user.id).single();if(error||!profile)return{session,user,profile:null,error:error||new Error("User profile not found.")};if(profile.active!==true){await client.auth.signOut();return{session:null,user:null,profile:null,error:new Error("Your MIS account is inactive.")};}return{session,user,profile,error:null};}
async function requireLogin(redirectPage="index.html"){const result=await getCurrentUserProfile();if(result.error||!result.session||!result.profile){window.location.href=redirectPage;return null;}return result;}
async function requireAdmin(redirectPage="home.html"){const result=await requireLogin();if(!result)return null;if(result.profile.role!=="Admin"){alert("Access denied. Administrator permission is required.");window.location.href=redirectPage;return null;}return result;}
async function login(){const username=document.getElementById("username").value.trim(),password=document.getElementById("password").value,message=document.getElementById("message"),loginButton=document.getElementById("loginButton");message.innerHTML="";if(!username||!password){message.innerHTML="Please enter User ID and Password.";return;}loginButton.disabled=true;loginButton.innerHTML="LOGGING IN...";try{const email=username.includes("@")==true?username.toLowerCase():username.toLowerCase()+"@hexadox-mis.local";const {data,error}=await client.auth.signInWithPassword({email,password});if(error){message.innerHTML=error.message;return;}if(!data||!data.session){message.innerHTML="Login succeeded but no session was created.";return;}const profileResult=await getCurrentUserProfile();if(profileResult.error||!profileResult.profile){await client.auth.signOut();message.innerHTML=profileResult.error?.message||"MIS user profile could not be loaded.";return;}message.innerHTML="Login successful.";setTimeout(()=>window.location.href="home.html",300);}catch(error){console.error("LOGIN ERROR:",error);message.innerHTML=error.message||"Login failed.";}finally{loginButton.disabled=false;loginButton.innerHTML="LOGIN";}}
async function logout(){try{await client.auth.signOut();}catch(error){console.error("Logout error:",error);}window.location.href="index.html";}

async function fixProductChartSecondaryAchievementSort(){try{if(!document.getElementById("productChart")||typeof charts==="undefined"||!charts.pr||typeof productMap==="undefined"||typeof getProductTargets!=="function"||typeof getHeaders!=="function"||typeof getDetails!=="function")return false;const year=+document.getElementById("year").value;const selected=+document.getElementById("month").value||new Date().getMonth()+1;const end=selected-1;if(end<4)return false;const targets=await getProductTargets(year,4,end);const priceCols={"4-2026":"price_apr_2026","5-2026":"price_may_2026","6-2026":"price_jun_2026","7-2026":"price_jul_2026","8-2026":"price_aug_2026","9-2026":"price_sep_2026","10-2026":"price_oct_2026","11-2026":"price_nov_2026","12-2026":"price_dec_2026","1-2027":"price_jan_2027","2-2027":"price_feb_2027","3-2027":"price_mar_2027"};const cols=[...new Set((targets||[]).map(t=>priceCols[`${t.month}-${t.year}`]).filter(Boolean))];if(!cols.length)return false;const {data:products,error}=await client.from("products").select(["id","product_name",...cols].join(",")).eq("active",true);if(error)throw error;const pm=new Map((products||[]).map(p=>[p.id,p]));const targetValue=new Map();(targets||[]).forEach(t=>{const p=pm.get(t.product_id),pts=Number(p?.[priceCols[`${t.month}-${t.year}`]])||0;targetValue.set(t.product_id,(targetValue.get(t.product_id)||0)+(Number(t.target_units)||0)*pts);});const headers=await getHeaders(year,4,end),details=await getDetails(headers.map(x=>x.id)),hm=new Map(headers.map(x=>[x.id,x])),secondaryValue=new Map();details.forEach(d=>{if(hm.has(d.entry_id))secondaryValue.set(d.product_id,(secondaryValue.get(d.product_id)||0)+(Number(d.secondary_value)||0));});const reverse=new Map([...productMap.entries()].map(([id,name])=>[name,id]));const labels=charts.pr.data.labels.slice();const order=labels.map((name,i)=>{const id=reverse.get(name),tv=targetValue.get(id)||0,sv=secondaryValue.get(id)||0;return{i,name,ach:tv?sv/tv:0};}).sort((a,b)=>a.ach-b.ach||a.name.localeCompare(b.name));charts.pr.data.labels=order.map(x=>x.name);charts.pr.data.datasets.forEach(ds=>{if(Array.isArray(ds.data))ds.data=order.map(x=>ds.data[x.i]);});charts.pr.update();return true;}catch(e){console.error("Secondary achievement sort error",e);return false;}}
if(document.getElementById("productChart")){let tries=0;const timer=setInterval(async()=>{tries++;if(await fixProductChartSecondaryAchievementSort()||tries>=20)clearInterval(timer);},500);}
